application: loveless-2014-5718
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

#html file  
- url: /index.html
  static_files: index.html
  upload: index.html

#css style file  
- url: /css.css
  static_files: css.css
  upload: css.css

#js file
- url: /js.js
  static_files: js.js
  upload: js.js

#image file
- url: /cindy.jpg
  static_files: cindy.jpg
  upload: cindy.jpg

#image file
- url: /img
  static_dir: img

#script
- url: /.*
  script: main.APP


